[package]
name = "netencode"
version = "1.0.0"
edition = "2021"

[dependencies]
nom = "5.1.1"
exec_helpers = { path = "exec-helpers" }
indexmap = "2.10.0"

[lib]
name = "netencode"
path = "netencode.rs"
